gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    manager_type: orm
    ttl: 604800  # 7 days (reduced from 30 days for security)
    token_parameter_name: refresh_token
