knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            redirect_route: app_google_callback
            redirect_params: {}
            # Stateless mode - no session required (compatible with JWT API)
            use_state: false
